//
//  CardInfoInteractor.swift
//  HSGallery
//
//  Created by YesVladess on 04.12.2019.
//  Copyright (c) 2019 YesVladess. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CardInfoInteractor: CardInfoBusinessLogic, CardInfoDataStore {
    
    var cardInfo2: CreatureViewModelProtocol?
    var presenter: CardInfoPresentationLogic?
    var router: CardInfoRoutingLogic?
    
    var cardInfo: CardModel?
    
    func getCard(_ name: String) {
        
        let myApi = HSGalleryRapidAPIService()
        
        myApi.getSingleCard(byName: name, completionHandler:
            { [unowned self] cards, error in
                if let errorDesc = error {
                    print(errorDesc)
                } else {
                    if cards?.count == 2 {
                    if let myCardInfo = cards?[1] {
                        self.cardInfo = myCardInfo
                        self.presenter?.presentCard(card: self.cardInfo!)
                    }
                    } else {
                        if let myCardInfo = cards?[0] {
                            self.cardInfo = myCardInfo
                            self.presenter?.presentCard(card: self.cardInfo!)
                        }
                    }
                }
        })
    }
    
    func showCard() {
        
        self.presenter?.showCard(card: self.cardInfo2!)
    }
}
