//
//  CardInfoPresenter.swift
//  HSGallery
//
//  Created by YesVladess on 04.12.2019.
//  Copyright (c) 2019 YesVladess. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CardInfoPresenter {
    
    weak var view: CardInfoDisplayLogic?
    
    private func formatCardFlavor(_ flavor: String?) -> String {
        if let cardFlavor = flavor {
            return cardFlavor
        }
        else {
            return "No flavor"
        }
    }
}

extension CardInfoPresenter: CardInfoPresentationLogic {
    
    func presentCard(card: CreatureViewModelProtocol) {
        
        // Во вью модели уже все отформатировано, просто прокидываем дальше
        let url = card.img
        let urlGold = card.img
        let cost = card.cost
        let health = card.health
        let attack = card.attack
        let rarity = card.rarity
        let text = card.text
        let flavor = ""
        
        view?.displayCard(url: url, urlGold: urlGold, cost: cost, health: health, attack: attack, rarity: rarity, text: text, flavor: flavor)
    }
}
