//
//  CardInfoInteractor.swift
//  HSGallery
//
//  Created by YesVladess on 04.12.2019.
//  Copyright (c) 2019 YesVladess. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CardInfoInteractor: CardInfoBusinessLogic, CardInfoDataStore
{
    var presenter: CardInfoPresentationLogic?
    var router: CardInfoRoutingLogic?
    
    var cardInfo: CardInfo?
    
    func getCard(_ name: String) {
        
        let myApi = HSGalleryRapidAPIService()
        
        myApi.getSingleCard(byName: name, completionHandler:
            { [weak self] cards, error in
                self!.cardInfo = cards![0]
                self!.presenter?.presentCard(card: self!.cardInfo!)
        })
    }
}
