//
//  CardInfoViewController.swift
//  HSGallery
//
//  Created by YesVladess on 04.12.2019.
//  Copyright (c) 2019 YesVladess. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CardInfoViewController: UIViewController {
    
    var interactor: CardInfoBusinessLogic?
    var router: (NSObjectProtocol & CardInfoRoutingLogic & CardInfoDataPassing)?
    
    // MARK: - Creating methods
    
    static func initFromDefaultStoryboard() -> CardInfoViewController? {
        let storyboard = UIStoryboard(name: "CardInfoViewController", bundle: nil)
        
        guard let vc = storyboard.instantiateInitialViewController() as? CardInfoViewController else {
            return nil
        }
        
        return vc
    }
    
    private func setupVc() {
        
        //    let request = CardInfo.Something.Request()
        //    interactor?.doSomething(request: request)
    }
    
    // MARK: Routing
    
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        textField.delegate = self
        setupVc()
    }
    
    // MARK: IBOutlets
    
    @IBOutlet weak var textField: UITextField!
    @IBOutlet weak var textView: UITextView!
    
}

extension CardInfoViewController: CardInfoDisplayLogic {
    
    func displayCardText(card: String) {
        
        textView.text = card
    }
}

extension CardInfoViewController: UITextFieldDelegate {
    
    func textFieldShouldReturn(_ textField: UITextField) -> Bool {
        textField.resignFirstResponder()
        return true
    }
    
    func textFieldDidEndEditing(_ textField: UITextField) {
        let textFromTextField: String = textField.text ?? ""
        interactor?.getCard(textFromTextField)
    }
}
