//
//  CardInfoInteractor.swift
//  HSGallery
//
//  Created by YesVladess on 04.12.2019.
//  Copyright (c) 2019 YesVladess. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CardInfoBusinessLogic
{
    func getCard(_ name: String)
}

protocol CardInfoDataStore
{
  //var name: String { get set }
}

class CardInfoInteractor: CardInfoBusinessLogic, CardInfoDataStore
{
  var presenter: CardInfoPresentationLogic?
    
    var name = ""
  
    func getCard(_ name: String) {
        
        let myApi = HSGalleryRapidAPIService()
        myApi.getSingleCard(byName: name ?? "", completionHandler:
            { cards, error in
//                self.textView.text = cards?[0].text
        })
    }
}
