//
//  CardInfoPresenter.swift
//  HSGallery
//
//  Created by YesVladess on 04.12.2019.
//  Copyright (c) 2019 YesVladess. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class CardInfoPresenter {
    
    weak var view: CardInfoDisplayLogic?
}

extension CardInfoPresenter: CardInfoPresentationLogic {
    func presentCard(card: CardInfo)
    {
        // Removing an underScore for card text
        var cardText = card.text
        cardText = cardText.replacingOccurrences(of: "_", with: " ")
        view?.displayCardText(card: cardText)
    }
}
